Confirm bosh is installed and the correct version

diff --git a/blite b/blite
--- a/blite
+++ b/blite
@@ -49,6 +49,14 @@ if [ ! $(command -v VBoxManage) ]; then
   exit 1
 fi
 
+if [ ! $(command -v bosh) ]; then
+  echo -e "\nBosh2 CLI not found! It must be installed before proceeding: https://bosh.io/docs/cli-v2.html#install"
+  exit 1
+elif [ -z "$(bosh -v | grep 'version 2.')" ]; then
+  echo -e "\nBosh seems to be installed, but is not the correct version. Version 2 is required https://bosh.io/docs/cli-v2.html#install"
+  exit 1
+fi
+
 print_director_ip () {
   echo "  BLITE_DIRECTOR_IP: $BLITE_DIRECTOR_IP"
 }
@@ -84,11 +92,11 @@ print_director_env_config () {
 
 print_env_info () {
   echo
-  echo "Your Bosh Director is now active! You may want to set/updatethe following environment variables:"
+  echo "Your Bosh Director is now active! You may want to set/update the following environment variables:"
   print_director_env_config
   echo "If you've already got these exported from a previous creation, don't forget to re-source as certs may have been updated!"
   echo "You can automatically setup your environment with the command:"
-  echo "eval $(blite env-eval)"
+  echo "  eval \$(blite env-eval)"
   echo
   echo "You probably also want to create a route so you can access your deployments from the host."
   echo "Depending on your cloud config these values may not be right. This script determines the CIDR of the Bosh Deployments"
@@ -99,7 +107,9 @@ print_env_info () {
   echo "   sudo route add -net $BLITE_BOSH_DEPLOYMENTS_CIDR     $BLITE_DIRECTOR_IP # Mac OS X"
   echo "   route add           $BLITE_BOSH_DEPLOYMENTS_CIDR     $BLITE_DIRECTOR_IP # Windows"
   echo
-  echo "You can automatically set the routes up if the above configuration looks right using blite route-add"
+  echo "You can automatically set the routes up if the above configuration looks right using:"
+  echo "  blite route-add"
+  echo
 }
 
 print_route_error() {
